### Get simple select

POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "SELECT 1"
}

### Get all tables

POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "SELECT * from system.tables;"
}
